### ISSUE TITLE
viewId is cleared upon every AD_BREAK_ events

### ISSUE THREAD

**Issue by Boubalou** [newrelic/video-agent-android#13]
Upon heavy usage of our video data by building different dashboards with multiple widgets, we noticed that some of our events had no viewIds during ads. 

After a bit of research, we stumbled upon this line in the library: https://github.com/newrelic/video-agent-android/blob/master/NewRelicVideoCore/src/main/java/com/newrelic/videoagent/core/tracker/NRVideoTracker.java#L197

The viewId is actually cleared on any AD_BREAK_* event, which kind of skew our data when playing around for widget related to ads.

What is the reasoning behind this approach? We noticed iOS also doing it, but not Web.

_Please note, I will enter the same issue in both repositories (iOS and Android)._

**Comment by asllop** [comment]
Fixed in https://github.com/newrelic/video-agent-android/commit/19aa5a718c4cb9afdaa778a2d3ee15a579c7b9ca
